# Generated by Django 5.2.7 on 2025-11-12 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0005_rename_mb_suppliment_masala'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=50)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('item', models.CharField(max_length=100)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('ingredients', models.TextField()),
                ('recipe', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/masala/')),
            ],
        ),
    ]
