# Generated by Django 5.2.7 on 2025-11-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0009_remove_add_product_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='assets\\images\\masala\x07dd_product'),
        ),
    ]
