# Generated by Django 5.2.7 on 2026-08-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=140)),
                ("image", models.ImageField(blank=True, upload_to="birthday/photos/")),
                ("alt_text", models.CharField(max_length=220)),
                ("caption", models.CharField(blank=True, max_length=240)),
                ("is_hero", models.BooleanField(db_index=True, default=False)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                "ordering": ("order", "title"),
                "indexes": [
                    models.Index(
                        fields=["is_hero", "order"],
                        name="gallery_pho_is_hero_855d67_idx",
                    )
                ],
            },
        ),
    ]
