# Generated by Django 5.2.7 on 2026-08-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TimelineEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("eyebrow", models.CharField(blank=True, max_length=80)),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField()),
                ("event_date", models.CharField(blank=True, max_length=80)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_published", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "ordering": ("order", "title"),
                "indexes": [
                    models.Index(
                        fields=["is_published", "order"],
                        name="timeline_ti_is_publ_b8f827_idx",
                    )
                ],
            },
        ),
    ]
