# Generated by Django 5.2.7 on 2026-08-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomeExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recipient_name",
                    models.CharField(
                        db_index=True, default="Vishuukhaa", max_length=120
                    ),
                ),
                ("nickname", models.CharField(default="Vishuu", max_length=80)),
                (
                    "birthday_label",
                    models.CharField(default="11 August", max_length=80),
                ),
                (
                    "hero_title",
                    models.CharField(default="Happy Birthday Vishuu", max_length=180),
                ),
                (
                    "hero_subtitle",
                    models.CharField(
                        default="A cinematic little universe made just for you.",
                        max_length=260,
                    ),
                ),
                (
                    "cta_label",
                    models.CharField(default="Begin the magic", max_length=80),
                ),
                (
                    "ending_message",
                    models.TextField(
                        default="May your year be as luminous, brave, and beautiful as your smile."
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "home experience",
                "ordering": ("-is_active", "-updated_at"),
            },
        ),
    ]
