# Generated by Django 5.2.3 on 2025-11-12 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0004_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MB_suppliment',
            new_name='Masala',
        ),
    ]
