# Generated by Django 5.2.7 on 2025-11-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0006_add_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_product',
            name='discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='add_product',
            name='mrp',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='add_product',
            name='prize',
            field=models.FloatField(null=True),
        ),
    ]
