# Generated by Django 5.2.7 on 2025-11-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0007_add_product_discount_add_product_mrp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_product',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
