# Generated by Django 5.2.7 on 2025-11-13 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0008_add_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_product',
            name='item',
        ),
    ]
