# Generated by Django 5.2.7 on 2025-11-16 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0010_alter_add_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_product',
            old_name='image',
            new_name='img',
        ),
    ]
