# Generated by Django 5.2.7 on 2025-11-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0011_rename_image_add_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='assets/images/masala/add_product'),
        ),
        migrations.DeleteModel(
            name='cart',
        ),
    ]
