# Generated by Django 5.2.7 on 2025-11-17 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0013_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='uid',
        ),
        migrations.DeleteModel(
            name='cart',
        ),
        migrations.DeleteModel(
            name='Masala',
        ),
        migrations.DeleteModel(
            name='order',
        ),
    ]
