# Generated by Django 5.2.7 on 2026-08-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(unique=True)),
                ("value", models.TextField(blank=True)),
                ("is_public", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "site setting",
                "verbose_name_plural": "site settings",
                "ordering": ("key",),
            },
        ),
        migrations.CreateModel(
            name="ThemeSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80, unique=True)),
                ("primary_color", models.CharField(default="#e879f9", max_length=32)),
                ("accent_color", models.CharField(default="#67e8f9", max_length=32)),
                ("glow_color", models.CharField(default="#f0abfc", max_length=32)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "ordering": ("-is_active", "name"),
            },
        ),
    ]
